//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACovid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acopio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acopio()
        {
            this.Donacion = new HashSet<Donacion>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDUbigeo { get; set; }
        public Nullable<int> IDDonantePersona { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string direccion_destino { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donacion> Donacion { get; set; }
        public virtual DonantePersona DonantePersona { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
