//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACovid
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandaDonación
    {
        public int ID { get; set; }
        public Nullable<int> IdPersonaBajosRecursos { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual PersonaBajosRecursos PersonaBajosRecursos { get; set; }
    }
}
