//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACovid
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonacionMedicina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonacionMedicina()
        {
            this.Donacion = new HashSet<Donacion>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string undad_medida { get; set; }
        public string laboratorio { get; set; }
        public string descripción { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donacion> Donacion { get; set; }
    }
}
