//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACovid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        public int ID { get; set; }
        public Nullable<int> IDPersonalAdmin { get; set; }
        public Nullable<int> IDUbigeo { get; set; }
        public Nullable<int> IDDonantePersona { get; set; }
        public Nullable<int> IDDonanteEmpresa { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
        public Nullable<int> IDDonacionDinero { get; set; }
        public Nullable<int> IDDonacionViveres { get; set; }
        public Nullable<int> IDDonacionMedicina { get; set; }
        public Nullable<int> IDAcopio { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Acopio Acopio { get; set; }
        public virtual DonacionDinero DonacionDinero { get; set; }
        public virtual DonacionMedicina DonacionMedicina { get; set; }
        public virtual DonacionViveres DonacionViveres { get; set; }
        public virtual DonanteEmpresa DonanteEmpresa { get; set; }
        public virtual DonantePersona DonantePersona { get; set; }
        public virtual PersonalAdministrativo PersonalAdministrativo { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
