//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACovid
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaTriaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonaTriaje()
        {
            this.Triaje = new HashSet<Triaje>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDPersonalGeneral { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Sintomas { get; set; }
        public string Descripción { get; set; }
        public string Ocupacion { get; set; }
        public string Direccion { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Edad { get; set; }
    
        public virtual PersonalGeneral PersonalGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Triaje> Triaje { get; set; }
    }
}
