//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACovid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Triaje
    {
        public int ID { get; set; }
        public Nullable<int> IDPersonalAdmin { get; set; }
        public Nullable<int> IDPersonaTriaje { get; set; }
        public Nullable<int> IDUbigeo { get; set; }
        public Nullable<System.DateTime> fecha_consulta { get; set; }
        public Nullable<System.DateTime> fecha_visita { get; set; }
        public string estado { get; set; }
    
        public virtual PersonalAdministrativo PersonalAdministrativo { get; set; }
        public virtual PersonaTriaje PersonaTriaje { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
